### ISSUE TITLE
Update to IdentityServer4 rc4 update1

### ISSUE THREAD

**Issue by damienbod** [damienbod/AspNet5IdentityServerAngularImplicitFlow#36]
Lots of breaking changes
- login changed (OK for multi app, single app routing problem since update)
- logout changed (OK)
- Config Scopes (OK)
- IProfileService changed (OK)
- ConsentModel changed (OK)
- Register new user redirects incorrectly (must test again)
- Consent shows double claims (OK)
- resource claims check returns a 403 (OK)
- roles missing from id_token (OK)
- claims missing from introspection result, cannot use claims on resource server (OK)

**Comment by damienbod** [comment]
https://github.com/IdentityServer/IdentityServer4.AccessTokenValidation/issues/36

**Comment by damienbod** [comment]
https://github.com/damienbod/AspNet5IdentityServerAngularImplicitFlow/tree/updateIdentityServerRc4

**Comment by leastprivilege** [comment]
done?

How long did it take?

**Comment by damienbod** [comment]
Microsoft.AspNetCore.Hosting.Internal.WebHost:Information: Request starting HTTP/1.1 GET http://localhost:44378/api/FileExplorer/ application/json 
Microsoft.AspNetCore.Hosting.Internal.WebHost:Information: Request starting HTTP/1.1 GET http://localhost:44318/.well-known/openid-configuration  
IdentityServer4.Hosting.IdentityServerMiddleware:Information: Invoking IdentityServer endpoint: IdentityServer4.Endpoints.DiscoveryEndpoint for /.well-known/openid-configuration
Microsoft.AspNetCore.Hosting.Internal.WebHost:Information: Request finished in 5.5779ms 200 application/json
'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\1.0.1\System.IO.Compression.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Microsoft.AspNetCore.Hosting.Internal.WebHost:Information: Request starting HTTP/1.1 POST http://localhost:44318/connect/introspect application/x-www-form-urlencoded 155
IdentityServer4.Hosting.IdentityServerMiddleware:Information: Invoking IdentityServer endpoint: IdentityServer4.Endpoints.IntrospectionEndpoint for /connect/introspect
Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommandBuilderFactory:Information: Executed DbCommand (0ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
PRAGMA foreign_keys=ON;
Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommandBuilderFactory:Information: Executed DbCommand (0ms) [Parameters=[@__id_0='?'], CommandType='Text', CommandTimeout='30']
SELECT "u"."Id", "u"."AccessFailedCount", "u"."ConcurrencyStamp", "u"."DataEventRecordsRole", "u"."Email", "u"."EmailConfirmed", "u"."IsAdmin", "u"."LockoutEnabled", "u"."LockoutEnd", "u"."NormalizedEmail", "u"."NormalizedUserName", "u"."PasswordHash", "u"."PhoneNumber", "u"."PhoneNumberConfirmed", "u"."SecuredFilesRole", "u"."SecurityStamp", "u"."TwoFactorEnabled", "u"."UserName"
FROM "AspNetUsers" AS "u"
WHERE "u"."Id" = @__id_0
LIMIT 1
IdentityServer4.Endpoints.IntrospectionEndpoint:Information: Success token introspection. Token status: active, for API name: securedFiles
Microsoft.AspNetCore.Hosting.Internal.WebHost:Information: Request finished in 23.4035ms 200 application/json
IdentityModel.AspNetCore.OAuth2Introspection.OAuth2IntrospectionMiddleware:Information: HttpContext.User merged via AutomaticAuthentication from authenticationScheme: Bearer.
IdentityModel.AspNetCore.OAuth2Introspection.OAuth2IntrospectionMiddleware:Information: AuthenticationScheme: Bearer was successfully authenticated.
IdentityModel.AspNetCore.ScopeValidation.ScopeValidationMiddleware:Information: Scopes found on current principal: scope: securedFiles
Microsoft.AspNetCore.Authorization.DefaultAuthorizationService:Information: Authorization was successful for user: ace69c61-3493-4f5d-8359-927e0d537889.
Microsoft.AspNetCore.Authorization.DefaultAuthorizationService:Information: Authorization was successful for user: ace69c61-3493-4f5d-8359-927e0d537889.
Microsoft.AspNetCore.Authorization.DefaultAuthorizationService:Information: Authorization failed for user: ace69c61-3493-4f5d-8359-927e0d537889.
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker:Warning: Authorization failed for the request at filter 'Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter'.
Microsoft.AspNetCore.Mvc.ChallengeResult:Information: Executing ChallengeResult with authentication schemes ().
IdentityModel.AspNetCore.OAuth2Introspection.OAuth2IntrospectionMiddleware:Information: AuthenticationScheme: Bearer was forbidden.
Microsoft.AspNetCore.Hosting.Internal.WebHost:Information: Request finished in 356.2955ms 403

**Comment by damienbod** [comment]
@leastprivilege still have some 403 Introspection problem from the resource servers, and want to clean up update the logout for a global logout. Want to update the blogs then. Will try to finish this weekend.

Greetings Damien

**Comment by damienbod** [comment]
https://github.com/IdentityServer/IdentityServer4/issues/531

**Comment by damienbod** [comment]
https://github.com/IdentityServer/IdentityServer4/issues/532
